function add_action(image_container_element){
    // Adds action to individual bo_unit's action section
    // Works via copying the image of image_container_element and appending it to the bo_unit
    var active_unit = document.querySelector('.active');
    var active_row = active_unit.querySelector('.row');
    var active_action = active_row.querySelector('.action');

    var img_test = document.createElement('img');
    img_test.setAttribute("onclick", "delete_action(this)");
    img_test.src = image_container_element.querySelector('img').src
    img_test.height = "70";
    img_test.width = "70";
    active_action.appendChild(img_test);

    // If the action was the first action in the bo_unit and the bo_unit is the last item in bo_container
    // Add another bo_unit (to prevent constantly clicking + Step button)
    var num_actions_in_bo_unit = active_action.querySelectorAll('img').length;
    if (num_actions_in_bo_unit == 1){
        // Check to see if bo_unit is the last one in bo_container
        // If it is, create and append a non-active bo_step
        var bo_container = active_unit.parentNode;
        var bo_units = bo_container.querySelectorAll('div .bo_unit'); // First element will be headers?
        var last_bo_unit = bo_units[bo_units.length - 1];
        if (last_bo_unit.id == active_unit.id){
            add_bo_unit(active=false);
        }

    }
} 
function add_bo_unit(active=true){
    // Creates blank bo_unit and appends it to the bo_container
    div_bo_unit = create_bo_unit(active);
    var bo_container = document.getElementById('bo_container');
    bo_container.appendChild(div_bo_unit);

}
function create_bo_unit(active=true){
    // Create bo_unit (Build Order step)
    var bo_unit_id = Math.floor(Math.random() * 100000);
    var div_bo_unit = document.createElement('div');
    div_bo_unit.setAttribute("id", "bo_unit_" + bo_unit_id);
    div_bo_unit.setAttribute("class", "container bo_unit");
    div_bo_unit.setAttribute("onclick", "set_active_bo_unit(bo_unit_" + bo_unit_id + ")");

    // Create .row for bootstrap styling
    var div_row = document.createElement('div');
    div_row.setAttribute("class", "row");

    // Populate Build Order Unit (Trigger, Time, Action, Notes, Delete, Insert Below)
    // Trigger, Time and Notes will be styled together under .bo_text
    var div_trigger = document.createElement('div');
    div_trigger.setAttribute("class", "bo_text col-xl-1");
    var p_trigger = document.createElement('p');
    p_trigger.setAttribute("contentEditable", "true");
    p_trigger.innerHTML = "                     ";
    div_trigger.appendChild(p_trigger);

    var div_time = document.createElement('div');
    div_time.setAttribute("class", "bo_text col-xl-1"); 
    var p_time = document.createElement('p');
    p_time.setAttribute("contentEditable", "true");
    p_time.innerHTML = "                     ";
    div_time.appendChild(p_time);

    var div_action = document.createElement('div');
    div_action.setAttribute("class", "action col-xl-4");
    var p_action = document.createElement('p');
    p_action.innerHTML = "";
    div_action.appendChild(p_action);

    var div_notes = document.createElement('div');
    div_notes.setAttribute("class", "bo_text col-xl-4");
    var p_notes = document.createElement('p');
    p_notes.setAttribute("contentEditable", "true");
    p_notes.innerHTML = "                     ";
    div_notes.appendChild(p_notes);

    var div_delete = document.createElement('div');
    div_delete.setAttribute("class", "delete col-xl-1");
    div_delete.setAttribute("onclick", "delete_bo_unit(this)");
    var img_delete = document.createElement('img');
    img_delete.height = "50";
    img_delete.width = "50";
    img_delete.src = "trash.png"
    div_delete.appendChild(img_delete);

    var div_insert = document.createElement('div');
    div_insert.setAttribute("class", "insert col-xl-1");
    div_insert.setAttribute("onclick", "insert_below_bo_unit(this)");
    var img_insert = document.createElement('img');
    img_insert.height = "50";
    img_insert.width = "50";
    img_insert.src = "edit.png"
    div_insert.appendChild(img_insert);

    // Populate row with components of bo_unit, append the row to bo_unit
    div_row.appendChild(div_trigger);
    div_row.appendChild(div_time);
    div_row.appendChild(div_action);
    div_row.appendChild(div_notes);
    div_row.appendChild(div_delete);
    div_row.appendChild(div_insert);
    div_bo_unit.append(div_row);

    // bo_units will be active unless they are auto generated by editing the last bo_unit for the first time
    if (active == true){
        set_active_bo_unit(div_bo_unit); 
    }
    
    return div_bo_unit;
}

function set_active_bo_unit(active_unit){
    // Applies the 'active' class to selected bo_unit. Removes 'active' class from all other bo_units.
    const allDivs = document.querySelectorAll('.bo_unit');
    // Remove all existing "active" classes and add "active" to active_unit
    if (active_unit) {
        allDivs.forEach(function(el){
            el.classList.remove('active');
        });
        active_unit.classList.add('active');
    }
}

function delete_action(action_to_delete){
    action_to_delete.remove();
}

function delete_bo_unit(unit_to_delete){
    //Deletes the container that unit_to_delete belongs to
    var grandparent_container = unit_to_delete.parentNode.parentNode;
    grandparent_container.remove();
}

function insert_below_bo_unit(unit_to_insert_below){
    var blank_bo_unit = create_bo_unit();
    var parent_bo_unit = unit_to_insert_below.parentNode.parentNode;

    // Insert new unit below unit that initiated the insert after
    parent_bo_unit.parentNode.insertBefore(blank_bo_unit, parent_bo_unit.nextSibling);
}
