function add_action(image_container_element){
    // Adds action to individual bo_unit's action section
    // Works via copying the image of image_container_element and appending it to the bo_unit
    var active_unit = document.querySelector('.active');
    var active_row = active_unit.querySelector('.row');
    var active_action = active_row.querySelector('.action');

    var img_test = document.createElement('img');
    img_test.setAttribute("onclick", "delete_action(this)");
    img_test.src = image_container_element.querySelector('img').src
    img_test.height = "70";
    img_test.width = "70";
    active_action.appendChild(img_test);

    // If the action was the first action in the bo_unit and the bo_unit is the last item in bo_container
    // Add another bo_unit (to prevent constantly clicking + Step button)
    var num_actions_in_bo_unit = active_action.querySelectorAll('img').length;
    console.log(num_actions_in_bo_unit);
    if (num_actions_in_bo_unit == 1){
        // Check to see if bo_unit is the last one in bo_container
        // If it is, create and append a non-active bo_step
        var bo_container = active_unit.parentNode;
        var bo_units = bo_container.querySelectorAll('div .bo_unit'); // First element will be headers
        console.log(bo_units);
        var last_bo_unit = bo_units[bo_units.length - 1];
        if (last_bo_unit.id == active_unit.id){
            add_bo_unit(active=false);
        }

    }
} 
function add_bo_unit(active=true){
    // Creates blank bo_unit and appends it to the bo_container
    div_bo_unit = create_bo_unit(active);
    var bo_container = document.getElementById('bo_container');
    bo_container.appendChild(div_bo_unit);

}
function create_bo_unit(active=true){
    // Create bo_unit (Build Order step)
    var bo_unit_id = Math.floor(Math.random() * 100000);
    var div_bo_unit = document.createElement('div');
    div_bo_unit.setAttribute("id", "bo_unit_" + bo_unit_id);
    div_bo_unit.setAttribute("class", "container bo_unit");
    div_bo_unit.setAttribute("onclick", "set_active_bo_unit(bo_unit_" + bo_unit_id + ")");

    // Create .row for bootstrap styling
    var div_row = document.createElement('div');
    div_row.setAttribute("class", "row");

    // Populate Build Order Unit (Trigger, Action, Notes, Delete, Insert Below)
    var div_trigger = document.createElement('div');
    div_trigger.setAttribute("class", "trigger col-xl-1");
    var p_trigger = document.createElement('p');
    p_trigger.setAttribute("contentEditable", "true");
    p_trigger.innerHTML = "                     ";
    div_trigger.appendChild(p_trigger);

    var div_action = document.createElement('div');
    div_action.setAttribute("class", "action col-xl-5");
    var p_action = document.createElement('p');
    p_action.innerHTML = "";
    div_action.appendChild(p_action);

    var div_notes = document.createElement('div');
    div_notes.setAttribute("class", "notes col-xl-4");
    var p_notes = document.createElement('p');
    p_notes.setAttribute("contentEditable", "true");
    p_notes.innerHTML = "                     ";
    div_notes.appendChild(p_notes);

    var div_delete = document.createElement('div');
    div_delete.setAttribute("class", "delete col-xl-1");
    div_delete.setAttribute("onclick", "delete_bo_unit(this)");
    var img_delete = document.createElement('img');
    img_delete.height = "50";
    img_delete.width = "50";
    img_delete.src = "trash.png"
    div_delete.appendChild(img_delete);

    var div_insert = document.createElement('div');
    div_insert.setAttribute("class", "insert col-xl-1");
    div_insert.setAttribute("onclick", "insert_below_bo_unit(this)");
    var img_insert = document.createElement('img');
    img_insert.height = "50";
    img_insert.width = "50";
    img_insert.src = "edit.png"
    div_insert.appendChild(img_insert);

    // Populate row with components of bo_unit, append the row to bo_unit
    div_row.appendChild(div_trigger);
    div_row.appendChild(div_action);
    div_row.appendChild(div_notes);
    div_row.appendChild(div_delete);
    div_row.appendChild(div_insert);
    div_bo_unit.append(div_row);

    // bo_units will be active unless they are auto generated by editing the last bo_unit for the first time
    if (active == true){
        set_active_bo_unit(div_bo_unit); 
    }
    
    return div_bo_unit;
}

function set_active_bo_unit(active_unit){
    // Applies the 'active' class to selected bo_unit. Removes 'active' class from all other bo_units.
    const allDivs = document.querySelectorAll('.bo_unit');
    // Remove all existing "active" classes and add "active" to active_unit
    if (active_unit) {
        allDivs.forEach(function(el){
            el.classList.remove('active');
        });
        active_unit.classList.add('active');
    }
}

function delete_action(action_to_delete){
    action_to_delete.remove();
}

function delete_bo_unit(unit_to_delete){
    //Deletes the container that unit_to_delete belongs to
    var grandparent_container = unit_to_delete.parentNode.parentNode;
    grandparent_container.remove();
}

function insert_below_bo_unit(unit_to_insert_below){
    console.log("insert ran"); //START HERE: Fix insert function
    console.log(unit_to_insert_below);

    var blank_bo_unit = create_bo_unit();
    var parent_bo_unit = unit_to_insert_below.parentNode.parentNode;

    // Insert new unit below unit that initiated the insert after
    parent_bo_unit.parentNode.insertBefore(blank_bo_unit, parent_bo_unit.nextSibling);
    console.log(parent_bo_unit);
}

function select_race(race_button){
    // Populate Action Selector depending on selected race
    var img_ele = race_button.querySelector('img');
    var race_ele = document.querySelector('#bo_race'); // BO metadata at top of page

    if (img_ele.id == "terran"){
        race_ele.innerHTML = "Race: Terran";
    }
    else if (img_ele.id == "zerg"){
        race_ele.innerHTML = "Race: Zerg";
    }
    else{ //protoss
        race_ele.innerHTML = "Race: Protoss";
    }
}

function set_grid_to_blank(){
    grid_0_0 = document.querySelector("#action_selector_grid_0_0");
    grid_0_0.src = "./icons/empty.png";
    grid_1_0 = document.querySelector("#action_selector_grid_1_0");
    grid_1_0.src = "./icons/empty.png";
    grid_2_0 = document.querySelector("#action_selector_grid_2_0");
    grid_2_0.src = "./icons/empty.png";
    grid_3_0 = document.querySelector("#action_selector_grid_3_0");
    grid_3_0.src = "./icons/empty.png";
    grid_4_0 = document.querySelector("#action_selector_grid_4_0");
    grid_4_0.src = "./icons/empty.png";
    grid_5_0 = document.querySelector("#action_selector_grid_5_0");
    grid_5_0.src = "./icons/empty.png";
    grid_6_0 = document.querySelector("#action_selector_grid_6_0");
    grid_6_0.src = "./icons/empty.png";
    grid_7_0 = document.querySelector("#action_selector_grid_7_0");
    grid_7_0.src = "./icons/empty.png";

    grid_0_1 = document.querySelector("#action_selector_grid_0_1");
    grid_0_1.src = "./icons/empty.png";
    grid_1_1 = document.querySelector("#action_selector_grid_1_1");
    grid_1_1.src = "./icons/empty.png";
    grid_2_1 = document.querySelector("#action_selector_grid_2_1");
    grid_2_1.src = "./icons/empty.png";
    grid_3_1 = document.querySelector("#action_selector_grid_3_1");
    grid_3_1.src = "./icons/empty.png";
    grid_4_1 = document.querySelector("#action_selector_grid_4_1");
    grid_4_1.src = "./icons/empty.png";
    grid_5_1 = document.querySelector("#action_selector_grid_5_1");
    grid_5_1.src = "./icons/empty.png";
    grid_6_1 = document.querySelector("#action_selector_grid_6_1");
    grid_6_1.src = "./icons/empty.png";
    grid_7_1 = document.querySelector("#action_selector_grid_7_1");
    grid_7_1.src = "./icons/empty.png";

    grid_0_2 = document.querySelector("#action_selector_grid_0_2");
    grid_0_2.src = "./icons/empty.png";
    grid_1_2 = document.querySelector("#action_selector_grid_1_2");
    grid_1_2.src = "./icons/empty.png";
    grid_2_2 = document.querySelector("#action_selector_grid_2_2");
    grid_2_2.src = "./icons/empty.png";
    grid_3_2 = document.querySelector("#action_selector_grid_3_2");
    grid_3_2.src = "./icons/empty.png";
    grid_4_2 = document.querySelector("#action_selector_grid_4_2");
    grid_4_2.src = "./icons/empty.png";
    grid_5_2 = document.querySelector("#action_selector_grid_5_2");
    grid_5_2.src = "./icons/empty.png";
    grid_6_2 = document.querySelector("#action_selector_grid_6_2");
    grid_6_2.src = "./icons/empty.png";
    grid_7_2 = document.querySelector("#action_selector_grid_7_2");
    grid_7_2.src = "./icons/empty.png";

    grid_0_3 = document.querySelector("#action_selector_grid_0_3");
    grid_0_3.src = "./icons/empty.png";
    grid_1_3 = document.querySelector("#action_selector_grid_1_3");
    grid_1_3.src = "./icons/empty.png";
    grid_2_3 = document.querySelector("#action_selector_grid_2_3");
    grid_2_3.src = "./icons/empty.png";
    grid_3_3 = document.querySelector("#action_selector_grid_3_3");
    grid_3_3.src = "./icons/empty.png";
    grid_4_3 = document.querySelector("#action_selector_grid_4_3");
    grid_4_3.src = "./icons/empty.png";
    grid_5_3 = document.querySelector("#action_selector_grid_5_3");
    grid_5_3.src = "./icons/empty.png";
    grid_6_3 = document.querySelector("#action_selector_grid_6_3");
    grid_6_3.src = "./icons/empty.png";
    grid_7_3 = document.querySelector("#action_selector_grid_7_3");
    grid_7_3.src = "./icons/empty.png";
}

function set_action_category(grid_type){
    // grid_type can be "structure", "unit", "upgrade", "misc"
    var race_ele = document.querySelector('#bo_race').textContent; // BO metadata at top of page

    // Reset the grid before writing to it
    set_grid_to_blank();

    console.log(race_ele);

    if (race_ele == "Race: Terran"){


    }else if (race_ele == "Race: Zerg"){
        if (grid_type == "structure"){
            grid_0_0 = document.querySelector("#action_selector_grid_0_0");
            grid_0_0.src = "./icons/hatchery.png";
            grid_1_0 = document.querySelector("#action_selector_grid_1_0");
            grid_1_0.src = "./icons/extractor.png";
            grid_2_0 = document.querySelector("#action_selector_grid_2_0");
            grid_2_0.src = "./icons/spawning_pool.png";
            grid_3_0 = document.querySelector("#action_selector_grid_3_0");
            grid_3_0.src = "./icons/evolution_chamber.png";
            grid_4_0 = document.querySelector("#action_selector_grid_4_0");
            grid_4_0.src = "./icons/roach_warren.png";
            grid_5_0 = document.querySelector("#action_selector_grid_5_0");
            grid_5_0.src = "./icons/baneling_nest.png";
            grid_6_0 = document.querySelector("#action_selector_grid_6_0");
            grid_6_0.src = "./icons/spine_crawler.png";
            grid_7_0 = document.querySelector("#action_selector_grid_7_0");
            grid_7_0.src = "./icons/spore_crawler.png";

            grid_0_1 = document.querySelector("#action_selector_grid_0_1");
            grid_0_1.src = "./icons/lair.png";
            grid_1_1 = document.querySelector("#action_selector_grid_1_1");
            grid_1_1.src = "./icons/hydralisk_den.png";
            grid_2_1 = document.querySelector("#action_selector_grid_2_1");
            grid_2_1.src = "./icons/lurker_den.png";
            grid_3_1 = document.querySelector("#action_selector_grid_3_1");
            grid_3_1.src = "./icons/spire.png";
            grid_4_1 = document.querySelector("#action_selector_grid_4_1");
            grid_4_1.src = "./icons/infestation_pit.png";
            grid_5_1 = document.querySelector("#action_selector_grid_5_1");
            grid_5_1.src = "./icons/nydus_network.png";
            grid_6_1 = document.querySelector("#action_selector_grid_6_1");
            grid_6_1.src = "./icons/nydus_worm.png";

            grid_0_2 = document.querySelector("#action_selector_grid_0_2");
            grid_0_2.src = "./icons/hive.png";
            grid_1_2 = document.querySelector("#action_selector_grid_1_2");
            grid_1_2.src = "./icons/greater_spire.png";
            grid_2_2 = document.querySelector("#action_selector_grid_2_2");
            grid_2_2.src = "./icons/ultralisk_cavern.png";
            
        }else if (grid_type == "unit"){
            grid_0_0 = document.querySelector("#action_selector_grid_0_0");
            grid_0_0.src = "./icons/drone.png";
            grid_1_0 = document.querySelector("#action_selector_grid_1_0");
            grid_1_0.src = "./icons/overlord.png";
            grid_2_0 = document.querySelector("#action_selector_grid_2_0");
            grid_2_0.src = "./icons/queen.png";
            grid_3_0 = document.querySelector("#action_selector_grid_3_0");
            grid_3_0.src = "./icons/empty.png";
            grid_4_0 = document.querySelector("#action_selector_grid_4_0");
            grid_4_0.src = "./icons/empty.png";
            grid_5_0 = document.querySelector("#action_selector_grid_5_0");
            grid_5_0.src = "./icons/empty.png";
            grid_6_0 = document.querySelector("#action_selector_grid_6_0");
            grid_6_0.src = "./icons/empty.png";
            grid_7_0 = document.querySelector("#action_selector_grid_7_0");
            grid_7_0.src = "./icons/empty.png";

            grid_0_1 = document.querySelector("#action_selector_grid_0_1");
            grid_0_1.src = "./icons/zergling.png";
            grid_1_1 = document.querySelector("#action_selector_grid_1_1");
            grid_1_1.src = "./icons/baneling.png";
            grid_2_1 = document.querySelector("#action_selector_grid_2_1");
            grid_2_1.src = "./icons/roach.png";
            grid_3_1 = document.querySelector("#action_selector_grid_3_1");
            grid_3_1.src = "./icons/ravager.png";
            grid_4_1 = document.querySelector("#action_selector_grid_4_1");
            grid_4_1.src = "./icons/hydralisk.png";
            grid_5_1 = document.querySelector("#action_selector_grid_5_1");
            grid_5_1.src = "./icons/lurker.png";
            grid_6_1 = document.querySelector("#action_selector_grid_6_1");
            grid_6_1.src = "./icons/mutalisk.png";
            grid_7_1 = document.querySelector("#action_selector_grid_7_1");
            grid_7_1.src = "./icons/corruptor.png";

            grid_0_2 = document.querySelector("#action_selector_grid_0_2");
            grid_0_2.src = "./icons/overseer.png";
            grid_1_2 = document.querySelector("#action_selector_grid_1_2");
            grid_1_2.src = "./icons/droperlord.png";
            grid_2_2 = document.querySelector("#action_selector_grid_2_2");
            grid_2_2.src = "./icons/swarm_host.png";
            grid_3_2 = document.querySelector("#action_selector_grid_3_2");
            grid_3_2.src = "./icons/infestor.png";
            grid_4_2 = document.querySelector("#action_selector_grid_4_2");
            grid_4_2.src = "./icons/viper.png";
            grid_5_2 = document.querySelector("#action_selector_grid_5_2");
            grid_5_2.src = "./icons/ultralisk.png";
            grid_6_2 = document.querySelector("#action_selector_grid_6_2");
            grid_6_2.src = "./icons/brood_lord.png";



        }else if (grid_type == "upgrade"){
            grid_0_0 = document.querySelector("#action_selector_grid_0_0");
            grid_0_0.src = "./icons/melee_attacks_level_one.gif";
            grid_1_0 = document.querySelector("#action_selector_grid_1_0");
            grid_1_0.src = "./icons/missile_attacks_level_one.gif";
            grid_2_0 = document.querySelector("#action_selector_grid_2_0");
            grid_2_0.src = "./icons/ground_carapace_level_one.gif";
            grid_3_0 = document.querySelector("#action_selector_grid_3_0");
            grid_3_0.src = "./icons/metabolic_boost.gif";
            grid_4_0 = document.querySelector("#action_selector_grid_4_0");
            grid_4_0.src = "./icons/pneumatized_carapace.gif";
            grid_5_0 = document.querySelector("#action_selector_grid_5_0");
            grid_5_0.src = "./icons/burrow.gif";
            grid_6_0 = document.querySelector("#action_selector_grid_6_0");
            grid_6_0.src = "./icons/melee_attacks_level_two.gif";
            grid_7_0 = document.querySelector("#action_selector_grid_7_0");
            grid_7_0.src = "./icons/missile_attacks_level_two.gif";

            grid_0_1 = document.querySelector("#action_selector_grid_0_1");
            grid_0_1.src = "./icons/ground_carapace_level_two.gif";
            grid_1_1 = document.querySelector("#action_selector_grid_1_1");
            grid_1_1.src = "./icons/flyer_attacks_level_one.gif";
            grid_2_1 = document.querySelector("#action_selector_grid_2_1");
            grid_2_1.src = "./icons/flyer_carapace_level_one.gif";
            grid_3_1 = document.querySelector("#action_selector_grid_3_1");
            grid_3_1.src = "./icons/flyer_attacks_level_two.gif";
            grid_4_1 = document.querySelector("#action_selector_grid_4_1");
            grid_4_1.src = "./icons/flyer_carapace_level_two.gif";
            grid_5_1 = document.querySelector("#action_selector_grid_5_1");
            grid_5_1.src = "./icons/centrifugal_hooks.gif";
            grid_6_1 = document.querySelector("#action_selector_grid_6_1");
            grid_6_1.src = "./icons/glial_reconstitution.gif";
            grid_7_1 = document.querySelector("#action_selector_grid_7_1");
            grid_7_1.src = "./icons/tunneling_claws.gif";

            grid_0_2 = document.querySelector("#action_selector_grid_0_2");
            grid_0_2.src = "./icons/grooved_spines.png";
            grid_1_2 = document.querySelector("#action_selector_grid_1_2");
            grid_1_2.src = "./icons/muscular_augments.png";
            grid_2_2 = document.querySelector("#action_selector_grid_2_2");
            grid_2_2.src = "./icons/pathogen_glands.gif";
            grid_3_2 = document.querySelector("#action_selector_grid_3_2");
            grid_3_2.src = "./icons/neural_parasite.png";
            grid_4_2 = document.querySelector("#action_selector_grid_4_2");
            grid_4_2.src = "./icons/melee_attacks_level_three.gif";
            grid_5_2 = document.querySelector("#action_selector_grid_5_2");
            grid_5_2.src = "./icons/missile_attacks_level_three.gif";
            grid_6_2 = document.querySelector("#action_selector_grid_6_2");
            grid_6_2.src = "./icons/ground_carapace_level_three.gif";
            grid_7_2 = document.querySelector("#action_selector_grid_7_2");
            grid_7_2.src = "./icons/flyer_attacks_level_three.gif";

            grid_0_3 = document.querySelector("#action_selector_grid_0_3");
            grid_0_3.src = "./icons/flyer_carapace_level_three.gif";
            grid_1_3 = document.querySelector("#action_selector_grid_1_3");
            grid_1_3.src = "./icons/chitinous_plating.gif";
            grid_2_3 = document.querySelector("#action_selector_grid_2_3");
            grid_2_3.src = "./icons/anabolic_synthesis.gif";
            grid_3_3 = document.querySelector("#action_selector_grid_3_3");
            grid_3_3.src = "./icons/adrenal_glands.gif";
            grid_4_3 = document.querySelector("#action_selector_grid_4_3");
            grid_4_3.src = "./icons/adaptive_talons.png";
            grid_5_3 = document.querySelector("#action_selector_grid_5_3");
            grid_5_3.src = "./icons/seismic_spines.png";
        }else if (grid_type == "misc"){
            grid_0_0 = document.querySelector("#action_selector_grid_0_0");
            grid_0_0.src = "./icons/scout.png";
            grid_1_0 = document.querySelector("#action_selector_grid_1_0");
            grid_1_0.src = "./icons/inject.png";
            grid_2_0 = document.querySelector("#action_selector_grid_2_0");
            grid_2_0.src = "./icons/creep.png";
        }
        
       
        

    }else{ //protoss

    }
}